title: Personal Webpage
email: bastian.scharnagl@gmail.com
description: >-
  A minimal space for research, projects, and ideas.

# Build settings
theme: jekyll-theme-minimal # Optional, but we are writing a custom layout below to keep it completely independent

# Navigation
navigation:
  - title: Home
    url: /
  - title: Exploration
    url: /exploration/
  - title: Collaboration
    url: /collaboration/
  - title: Creation
    url: /creation/
  - title: Inspiration
    url: /inspiration/